### ISSUE TITLE
iam superfast ⚡

### ISSUE THREAD

**Issue by athrvvvv** [ickyicky/fasttyper#2]
accuracy : 100.0%
enterrrrrr...enterrrrrr...enterrrrrr...

![record_000015_Trim](https://user-images.githubusercontent.com/98272709/189627225-f0d33e34-bce5-4a80-8f75-1d3862134bd0.gif)

**Comment by ickyicky** [comment]
wow so fast 🗲🗲😯😯
fixed in 2.3.2 which is already available in pip
